### PR TITLE
added data file in pip package

### PR DESCRIPTION
**Pull request by R1j1t**
I had a similar issue as described in #217 with below stack trace:
```bash
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 10
      8 from rxn_network.core.composition import Composition
      9 from rxn_network.costs.softplus import Softplus
---> 10 from rxn_network.thermo.chempot_diagram import ChemicalPotentialDiagram
     11 from rxn_network.entries.entry_set import GibbsEntrySet
     12 from rxn_network.enumerators.basic import BasicEnumerator, BasicOpenEnumerator

File /python3.10/site-packages/rxn_network/thermo/chempot_diagram.py:14
     11 from pymatgen.core.composition import Element
     12 from scipy.spatial import HalfspaceIntersection, KDTree
---> 14 from rxn_network.entries.entry_set import GibbsEntrySet
     17 class ChemicalPotentialDiagram(ChempotDiagram):
     18     """
     19     This class is an extension of the ChemicalPotentialDiagram class from pymatgen.
     20     Several features have been added to the original class for the purpose of
   (...)
     31         143(37), 15185-15194. https://doi.org/10.1021/jacs.1c06229
     32     """

File /python3.10/site-packages/rxn_network/entries/entry_set.py:26
     23 from tqdm import tqdm
     25 from rxn_network.core.composition import Composition
---> 26 from rxn_network.entries.barin import BarinReferenceEntry
     27 from rxn_network.entries.corrections import CarbonateCorrection
     28 from rxn_network.entries.experimental import ExperimentalReferenceEntry

File /python3.10/site-packages/rxn_network/entries/barin.py:10
      7 from pymatgen.entries.computed_entries import EnergyAdjustment
      9 from rxn_network.core.composition import Composition
---> 10 from rxn_network.data import PATH_TO_BARIN, load_experimental_data
     11 from rxn_network.entries.experimental import ExperimentalReferenceEntry
     13 G_COMPOUNDS = load_experimental_data(PATH_TO_BARIN / "compounds.json.gz")

File /python3.10/site-packages/rxn_network/data/__init__.py:16
     13 PATH_TO_FREED = cwd / "freed"
     14 PATH_TO_NIST = cwd / "nist"
---> 16 G_ELEMS = loadfn(cwd / "elements.json")
     19 def load_experimental_data(fn: Union[str, Path]) -> Dict[str, Dict[float, Any]]:
     20     """
     21     Load experimental data from a json file.
     22 
     23     Args:
     24         fn: The filename of the json file
     25     """

File /python3.10/site-packages/monty/serialization.py:63, in loadfn(fn, fmt, *args, **kwargs)
     61         return msgpack.load(fp, *args, **kwargs)  # pylint: disable=E1101
     62 else:
---> 63     with zopen(fn, "rt") as fp:
     64         if fmt == "yaml":
     65             if YAML is None:

File /python3.10/site-packages/monty/io.py:45, in zopen(filename, *args, **kwargs)
     43 if ext in (".XZ", ".LZMA"):
     44     return lzma.open(filename, *args, **kwargs)
---> 45 return open(filename, *args, **kwargs)

FileNotFoundError: [Errno 2] No such file or directory: '/python3.10/site-packages/rxn_network/data/elements.json'
```

If you include a `MANIFEST.in` as mentioned [here](https://packaging.python.org/en/latest/guides/using-manifest-in/), I think it should solve the issue. Please let me know if any changes need to be made to the PR, I am happy to contribute!

### CODE REVIEW

**Comment by mattmcdermott** [comment]
Wow, thank you @R1j1t! To be completely honest, I didn't know this could be an issue when building a source distribution. Thank you for adding the file and needed line, it is much appreciated :)

**Comment by mattmcdermott** [comment]
I'm going to merge this PR; disregard failing tests (have a couple small unrelated bugs to fix).

**Comment by R1j1t** [comment]
Happy to help @mattmcdermott! Thanks for the awesome documentation and package!

**Comment by mattmcdermott** [comment]
Thanks, I am glad you like it! And thank you for being a contributor :)

**Comment by mattmcdermott** [comment]
New version 7.0.1 on PyPI. Let me know if it works?

**Pull request merged**
